/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrackerRouteImport } from './routes/_app/tracker'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppReelsRouteImport } from './routes/_app/reels'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPregnancyRouteImport } from './routes/_app/pregnancy'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppLearnRouteImport } from './routes/_app/learn'
import { Route as AppExpertsRouteImport } from './routes/_app/experts'
import { Route as AppExpertPortalRouteImport } from './routes/_app/expert-portal'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppLearnSlugRouteImport } from './routes/_app/learn.$slug'
import { Route as AppCommunitySlugRouteImport } from './routes/_app/community.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackerRoute = AppTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPregnancyRoute = AppPregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertsRoute = AppExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertPortalRoute = AppExpertPortalRouteImport.update({
  id: '/expert-portal',
  path: '/expert-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnSlugRoute = AppLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppCommunitySlugRoute = AppCommunitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppCommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/community': typeof AppCommunityRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expert-portal': typeof AppExpertPortalRoute
  '/experts': typeof AppExpertsRoute
  '/learn': typeof AppLearnRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/pregnancy': typeof AppPregnancyRoute
  '/profile': typeof AppProfileRoute
  '/reels': typeof AppReelsRoute
  '/search': typeof AppSearchRoute
  '/tracker': typeof AppTrackerRoute
  '/community/$slug': typeof AppCommunitySlugRoute
  '/learn/$slug': typeof AppLearnSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/community': typeof AppCommunityRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expert-portal': typeof AppExpertPortalRoute
  '/experts': typeof AppExpertsRoute
  '/learn': typeof AppLearnRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/pregnancy': typeof AppPregnancyRoute
  '/profile': typeof AppProfileRoute
  '/reels': typeof AppReelsRoute
  '/search': typeof AppSearchRoute
  '/tracker': typeof AppTrackerRoute
  '/community/$slug': typeof AppCommunitySlugRoute
  '/learn/$slug': typeof AppLearnSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/community': typeof AppCommunityRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expert-portal': typeof AppExpertPortalRoute
  '/_app/experts': typeof AppExpertsRoute
  '/_app/learn': typeof AppLearnRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pregnancy': typeof AppPregnancyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reels': typeof AppReelsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/tracker': typeof AppTrackerRoute
  '/_app/community/$slug': typeof AppCommunitySlugRoute
  '/_app/learn/$slug': typeof AppLearnSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/community'
    | '/dashboard'
    | '/expert-portal'
    | '/experts'
    | '/learn'
    | '/notifications'
    | '/pregnancy'
    | '/profile'
    | '/reels'
    | '/search'
    | '/tracker'
    | '/community/$slug'
    | '/learn/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/community'
    | '/dashboard'
    | '/expert-portal'
    | '/experts'
    | '/learn'
    | '/notifications'
    | '/pregnancy'
    | '/profile'
    | '/reels'
    | '/search'
    | '/tracker'
    | '/community/$slug'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/expert-portal'
    | '/_app/experts'
    | '/_app/learn'
    | '/_app/notifications'
    | '/_app/pregnancy'
    | '/_app/profile'
    | '/_app/reels'
    | '/_app/search'
    | '/_app/tracker'
    | '/_app/community/$slug'
    | '/_app/learn/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tracker': {
      id: '/_app/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AppTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pregnancy': {
      id: '/_app/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof AppPregnancyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experts': {
      id: '/_app/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof AppExpertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expert-portal': {
      id: '/_app/expert-portal'
      path: '/expert-portal'
      fullPath: '/expert-portal'
      preLoaderRoute: typeof AppExpertPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/$slug': {
      id: '/_app/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AppLearnSlugRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/community/$slug': {
      id: '/_app/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof AppCommunitySlugRouteImport
      parentRoute: typeof AppCommunityRoute
    }
  }
}

interface AppCommunityRouteChildren {
  AppCommunitySlugRoute: typeof AppCommunitySlugRoute
}

const AppCommunityRouteChildren: AppCommunityRouteChildren = {
  AppCommunitySlugRoute: AppCommunitySlugRoute,
}

const AppCommunityRouteWithChildren = AppCommunityRoute._addFileChildren(
  AppCommunityRouteChildren,
)

interface AppLearnRouteChildren {
  AppLearnSlugRoute: typeof AppLearnSlugRoute
}

const AppLearnRouteChildren: AppLearnRouteChildren = {
  AppLearnSlugRoute: AppLearnSlugRoute,
}

const AppLearnRouteWithChildren = AppLearnRoute._addFileChildren(
  AppLearnRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppCommunityRoute: typeof AppCommunityRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpertPortalRoute: typeof AppExpertPortalRoute
  AppExpertsRoute: typeof AppExpertsRoute
  AppLearnRoute: typeof AppLearnRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPregnancyRoute: typeof AppPregnancyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReelsRoute: typeof AppReelsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTrackerRoute: typeof AppTrackerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppCommunityRoute: AppCommunityRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExpertPortalRoute: AppExpertPortalRoute,
  AppExpertsRoute: AppExpertsRoute,
  AppLearnRoute: AppLearnRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPregnancyRoute: AppPregnancyRoute,
  AppProfileRoute: AppProfileRoute,
  AppReelsRoute: AppReelsRoute,
  AppSearchRoute: AppSearchRoute,
  AppTrackerRoute: AppTrackerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
